// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Optimus.Infrastructure.Persistence;

#nullable disable

namespace Optimus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OptimusDbContext))]
    [Migration("20260811205000_DetentionBillingNullableManifest")]
    partial class DetentionBillingNullableManifest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model captured in OptimusDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
