// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optimus.Infrastructure.Persistence;

#nullable disable

namespace Optimus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OptimusDbContext))]
    [Migration("20260806030911_Phase1Identity")]
    partial class Phase1Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Optimus.Domain.Entities.Barangay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("barangays", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ConsigneeBrokerRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReferralCodeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ReferralCodeId");

                    b.HasIndex("ConsigneeId", "BrokerId")
                        .IsUnique();

                    b.ToTable("consignee_broker_relationships", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.PendingUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AcceptanceToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DisabledUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("ShippingLineAdminId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ShippingLineId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceToken")
                        .IsUnique();

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("ShippingLineAdminId");

                    b.HasIndex("ShippingLineId");

                    b.ToTable("pending_users", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ReferralCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ConsigneeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ConsigneeId");

                    b.ToTable("referral_codes", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.RolePermissionConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ShippingLineId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingLineId", "Role", "PermissionKey")
                        .IsUnique();

                    b.ToTable("role_permission_configurations", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ShippingLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedAdminUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BrandColor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PortalConfigJson")
                        .HasColumnType("json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminUserId");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.ToTable("shipping_lines", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ShippingLineConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("ShippingLineId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingLineId", "Key")
                        .IsUnique();

                    b.ToTable("shipping_line_configurations", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ManagedShippingLineId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("PasswordResetOtpExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetOtpHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("ShippingLineAdminId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagedShippingLineId");

                    b.HasIndex("ShippingLineAdminId");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Optimus.Domain.Entities.UserShippingLinePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("LastSelectedShippingLineId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LastSelectedShippingLineId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_shipping_line_preferences", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Broker", b =>
                {
                    b.HasBaseType("Optimus.Domain.Entities.User");

                    b.Property<Guid?>("ActiveWorkspaceConsigneeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BusinessAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasIndex("ActiveWorkspaceConsigneeId");

                    b.HasDiscriminator().HasValue("broker");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Consignee", b =>
                {
                    b.HasBaseType("Optimus.Domain.Entities.User");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasDiscriminator().HasValue("consignee");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.StaffUser", b =>
                {
                    b.HasBaseType("Optimus.Domain.Entities.User");

                    b.Property<string>("Department")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.ToTable("users", t =>
                        {
                            t.Property("Department")
                                .HasColumnName("StaffUser_Department");
                        });

                    b.HasDiscriminator().HasValue("staff");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.TerminalTeamUser", b =>
                {
                    b.HasBaseType("Optimus.Domain.Entities.User");

                    b.Property<string>("Department")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("TerminalPermissionsJson")
                        .HasColumnType("json");

                    b.HasDiscriminator().HasValue("terminal_team");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Trucker", b =>
                {
                    b.HasBaseType("Optimus.Domain.Entities.User");

                    b.Property<DateTime?>("ApiTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApiTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("TruckPlateNumber")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasDiscriminator().HasValue("trucker");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Barangay", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.City", "City")
                        .WithMany("Barangays")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.City", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ConsigneeBrokerRelationship", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optimus.Domain.Entities.Consignee", "Consignee")
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optimus.Domain.Entities.ReferralCode", "ReferralCode")
                        .WithMany()
                        .HasForeignKey("ReferralCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Broker");

                    b.Navigation("Consignee");

                    b.Navigation("ReferralCode");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.PendingUser", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.User", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Optimus.Domain.Entities.User", "ShippingLineAdmin")
                        .WithMany()
                        .HasForeignKey("ShippingLineAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Optimus.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany()
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("ShippingLine");

                    b.Navigation("ShippingLineAdmin");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Province", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.Region", "Region")
                        .WithMany("Provinces")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ReferralCode", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.Consignee", "Consignee")
                        .WithMany()
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consignee");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.RolePermissionConfiguration", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ShippingLine", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.User", "AssignedAdminUser")
                        .WithMany()
                        .HasForeignKey("AssignedAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedAdminUser");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ShippingLineConfiguration", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.ShippingLine", "ShippingLine")
                        .WithMany("Configurations")
                        .HasForeignKey("ShippingLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingLine");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.User", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.ShippingLine", "ManagedShippingLine")
                        .WithMany()
                        .HasForeignKey("ManagedShippingLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Optimus.Domain.Entities.User", "ShippingLineAdmin")
                        .WithMany()
                        .HasForeignKey("ShippingLineAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedShippingLine");

                    b.Navigation("ShippingLineAdmin");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.UserShippingLinePreference", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.ShippingLine", "LastSelectedShippingLine")
                        .WithMany()
                        .HasForeignKey("LastSelectedShippingLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Optimus.Domain.Entities.User", "User")
                        .WithOne("ShippingLinePreference")
                        .HasForeignKey("Optimus.Domain.Entities.UserShippingLinePreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastSelectedShippingLine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Broker", b =>
                {
                    b.HasOne("Optimus.Domain.Entities.Consignee", "ActiveWorkspaceConsignee")
                        .WithMany()
                        .HasForeignKey("ActiveWorkspaceConsigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveWorkspaceConsignee");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.City", b =>
                {
                    b.Navigation("Barangays");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Region", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.ShippingLine", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Optimus.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ShippingLinePreference");
                });
#pragma warning restore 612, 618
        }
    }
}
