// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Optimus.Infrastructure.Persistence;

#nullable disable

namespace Optimus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OptimusDbContext))]
    [Migration("20260808220000_AccreditationCertificate")]
    partial class AccreditationCertificate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);
#pragma warning restore 612, 618
        }
    }
}
