import type { DocumentTemplateTypeId } from '../../../shared/documentTemplateTypes';

export type BlockGroup = Record<string, { name: string }>;

export const DOCUMENT_BLOCK_GROUPS: Record<string, BlockGroup> = {
  'Headers & Titles': {
    header_banner: { name: 'Header Banner' },
    heading: { name: 'Heading' },
    logo: { name: 'Logo' },
  },
  Content: {
    text: { name: 'Text Block' },
    field_label: { name: 'Field Label' },
    field_value: { name: 'Field Value' },
    placeholder: { name: 'Dynamic Field' },
    info_row: { name: 'Label + Value (combined)' },
    two_column: { name: 'Two Columns' },
  },
  'Data Tables': {
    table: { name: 'Data Table' },
  },
  Layout: {
    divider: { name: 'Divider' },
    spacer: { name: 'Spacer' },
    border_box: { name: 'Border Box' },
  },
  'Signatures & Codes': {
    signature: { name: 'Signature Block' },
    qr_code: { name: 'QR Code' },
    image: { name: 'Image' },
  },
  Footer: {
    footer: { name: 'Footer' },
  },
};

export type PlaceholderGroups = Record<string, Record<string, string>>;

const COMMON: PlaceholderGroups = {
  System: {
    'generated.date': 'Generated Date',
    'generated.by': 'Generated By',
    'company.name': 'Company Name',
    'document.verification_url': 'Verification Link (QR Code)',
  },
};

export const DOCUMENT_PLACEHOLDERS: Record<string, PlaceholderGroups> = {
  NOA: {
    Document: {
      'noa.number': 'NOA Number',
      'noa.bl_number': 'BL Number',
      'noa.vessel_number': 'Vessel Number',
      'noa.eta': 'ETA',
      'noa.port_location': 'Port Location',
      'noa.container_count': 'Container Count',
    },
    Consignee: {
      'consignee.name': 'Consignee Name',
      'consignee.email': 'Consignee Email',
    },
    ...COMMON,
    Tables: {
      'containers.table': 'Containers Table',
    },
  },
  EDO: {
    Document: {
      'edo.status': 'Document Status',
      'edo.document_title': 'Document Title',
      'edo.document_subtitle': 'Document Subtitle',
      'edo.port_directive': 'Port Operations Directive',
    },
    'Manifest & Registry': {
      'manifest.number': 'Manifest Number',
      'manifest.bl_number': 'BL Number',
      'noa.number': 'Registry Number (NOA)',
    },
    Parties: {
      'consignee.name': 'Consignee / Notify Party',
      'broker.name': 'Broker Name',
      'shipping.line': 'Shipping Line / Carrier',
      'vessel.display': 'Vessel / Voyage',
    },
    'Company & Platform': {
      'platform.brand': 'Platform Brand',
      'platform.tagline': 'Platform Tagline',
      'company.name': 'Company Name',
    },
    Signatures: {
      'signatures.authorized_title': 'Authorized Rep. Title',
      'signatures.authorized_company': 'Authorized Rep. Company',
      'signatures.prepared_title': 'Prepared By Title',
      'signatures.prepared_by': 'Prepared By Name',
      'signatures.received_title': 'Received By Title',
    },
    ...COMMON,
    Tables: {
      'containers.table': 'Containers Table',
    },
  },
  BL: {
    Document: {
      'manifest.number': 'Manifest Number',
      'manifest.bl_number': 'BL Number',
    },
    ...COMMON,
    Tables: {
      'containers.table': 'Containers Table',
    },
  },
  Billing: {
    Document: {
      'billing.amount_primary': 'Amount (Primary)',
      'billing.amount_secondary': 'Amount (Secondary)',
      'billing.status': 'Billing Status',
      'billing.note': 'Billing Note',
      'billing.exchange_rate_display': 'Exchange Rate',
      'billing.total_amount_display': 'Total Amount',
      'billing.total_amount_usd': 'Total Amount (USD)',
    },
    Manifest: {
      'manifest.number': 'Manifest Number',
      'manifest.bl_number': 'BL Number',
    },
    Consignee: {
      'consignee.name': 'Consignee Name',
      'consignee.address': 'Consignee Address',
      'consignee.email': 'Consignee Email',
    },
    ...COMMON,
    Tables: {
      'charges.table': 'Charges Table',
    },
  },
  OR: {
    Document: {
      'receipt.number': 'Receipt Number',
      'receipt.amount': 'Receipt Amount',
    },
    ...COMMON,
  },
  Certificate: {
    Document: {
      'certificate.title': 'Certificate Title',
      'certificate.body': 'Certificate Body',
    },
    ...COMMON,
  },
};

export function placeholdersForType(documentType: string): PlaceholderGroups {
  return DOCUMENT_PLACEHOLDERS[documentType] ?? COMMON;
}

type LayoutElement = Record<string, unknown>;
export type DocumentLayout = { canvas: Record<string, unknown>; elements: LayoutElement[] };

function elId() {
  return `el_${Math.random().toString(16).slice(2, 10)}`;
}

function makeElement(type: string, order: number, config: LayoutElement = {}): LayoutElement {
  return {
    id: elId(),
    type,
    order,
    content: '',
    placeholder: '',
    label: '',
    style: {
      fontSize: 12,
      fontWeight: 'normal',
      textAlign: 'left',
      color: '#000000',
      backgroundColor: 'transparent',
      padding: 0,
      marginTop: 0,
      marginRight: 0,
      marginBottom: 8,
      marginLeft: 0,
    },
    position: { x: 48, y: 48, width: 698 },
    config: {},
    ...config,
  };
}

function defaultCanvas(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    width: 794,
    height: 1123,
    paperSize: 'A4',
    orientation: 'portrait',
    layoutMode: 'free',
    backgroundColor: '#ffffff',
    margin: { top: 48, right: 48, bottom: 48, left: 48 },
    borderColor: '#1e3a5f',
    showPageBorder: true,
    showMarginGuides: true,
    ...overrides,
  };
}

function defaultEdoLayout(): DocumentLayout {
  const canvas = defaultCanvas({
    orientation: 'landscape',
    width: 1123,
    height: 794,
    margin: { top: 24, right: 24, bottom: 24, left: 24 },
    showPageBorder: false,
    showMarginGuides: false,
  });
  const w = 1075;

  return {
    canvas,
    elements: [
      makeElement('border_box', 1, {
        content: ' ',
        position: { x: 24, y: 24, width: w, height: 72 },
        style: { backgroundColor: '#0f172a', borderColor: '#0f172a', borderWidth: 0, padding: 0 },
      }),
      makeElement('field_label', 2, {
        label: '{{ platform.brand }}',
        position: { x: 48, y: 36, width: 320 },
        style: { fontSize: 20, fontWeight: 'bold', color: '#ffffff', marginBottom: 0, letterSpacing: 3 },
      }),
      makeElement('field_label', 4, {
        label: '{{ edo.document_title }}',
        position: { x: 620, y: 40, width: 460 },
        style: { fontSize: 13, fontWeight: 'normal', color: '#ffffff', textAlign: 'right', marginBottom: 0 },
      }),
      makeElement('field_value', 8, {
        placeholder: 'manifest.bl_number',
        position: { x: 48, y: 126, width: 300 },
        style: { fontSize: 11, fontWeight: 'bold', color: '#0f172a', marginBottom: 0 },
      }),
      makeElement('field_value', 15, {
        placeholder: 'consignee.name',
        position: { x: 48, y: 184, width: 700 },
        style: { fontSize: 16, fontWeight: 'bold', color: '#0f172a', marginBottom: 0 },
      }),
      makeElement('table', 21, {
        placeholder: 'containers.table',
        columns: [
          'NO.',
          'CONTAINER NUMBER',
          'SIZE',
          'TYPE',
          'SEAL',
          'NAME OF HAULER',
          'PLATE NO.',
          'OPTIMUS REF NO.',
          'DEMURRAGE VALIDITY',
          'RETURN EMPTY TO',
        ],
        columnWidths: [4, 11, 7, 5, 5, 11, 7, 14, 11, 25],
        position: { x: 24, y: 310, width: w },
      }),
      makeElement('text', 23, {
        content: '{{ edo.port_directive }}',
        position: { x: 48, y: 538, width: 1000 },
        style: { fontSize: 9, color: '#334155', lineHeight: 1.5 },
      }),
    ],
  };
}

function genericLayout(label: string): DocumentLayout {
  return {
    canvas: defaultCanvas(),
    elements: [
      makeElement('header_banner', 1, {
        content: label,
        subtitle: 'Document Template',
        style: { textAlign: 'center', backgroundColor: '#1e3a5f', color: '#ffffff', fontSize: 20, padding: 20 },
      }),
      makeElement('text', 2, {
        content: 'Design your document by adding elements from the palette.',
        style: { textAlign: 'center', fontSize: 12, color: '#444444' },
      }),
    ],
  };
}

export function defaultDocumentLayout(documentType: string): DocumentLayout {
  if (documentType === 'EDO') return defaultEdoLayout();
  return genericLayout(documentType);
}

export function parseDocumentLayout(
  layoutJson: string | null | undefined,
  documentType: DocumentTemplateTypeId | string,
  paperSize: string,
  orientation: string,
): DocumentLayout {
  if (layoutJson) {
    try {
      const parsed = JSON.parse(layoutJson) as DocumentLayout;
      if (parsed.canvas && parsed.elements) return parsed;
    } catch {
      /* fall through */
    }
  }
  const layout = defaultDocumentLayout(documentType);
  layout.canvas.paperSize = paperSize || layout.canvas.paperSize;
  layout.canvas.orientation = orientation || layout.canvas.orientation;
  return layout;
}

export function serializeDocumentLayout(layout: DocumentLayout): string {
  return JSON.stringify(layout);
}

declare global {
  interface Window {
    initDocumentTemplateBuilder?: () => void;
    documentTemplateBuilderSave?: () => void;
    documentTemplateBuilderPreview?: () => void;
    dtToast?: (message: string, type?: string) => void;
  }
}
